
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: my-express-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file:
      - .env
    command: npm start
